name: Check Combined Status

on:
  workflow_run:
    workflows: ["Scanning code with SonarCloud", "Continuous Integration (CI)", "Scorecard supply-chain security"]
    types:
      - completed
    branches:
      - master

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check combined status of workflows
        id: check-status
        uses: actions/github-script@v6
        with:
          script: |
            const { data: status } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'master',
            });

            const requiredWorkflows = ["Scanning code with SonarCloud", "Continuous Integration (CI)", "Scorecard supply-chain security"];
            const allSuccess = status.statuses.every(status => status.state === 'success' && requiredWorkflows.includes(status.context));

            if (allSuccess) {
              console.log('All required workflows succeeded. Triggering deployment...');
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'deploy.yml',  # Nama file workflow deployment
                ref: 'master',
              });
            } else {
              console.log('Not all required workflows succeeded. Skipping deployment.');
            }