jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set permission for gradlew
        run: chmod +x gradlew
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"
          cache: "gradle"
      - name: Run unit tests
        run: ./gradlew test
