name: Deploy to Koyeb

on:
  workflow_run:
    workflows: ["Scanning code with SonarCloud", "Continuous Integration (CI)", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master' &&
      contains(fromJson('["Scanning code with SonarCloud", "Continuous Integration (CI)", "Scorecard supply-chain security"]'), github.event.workflow_run.name)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Deploy to Koyeb
        run: koyeb service update eshop --git-redeploy
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}