name: Deploy to Koyeb

on:
  workflow_run:
    workflows: ["Scanning code with SonarCloud"]
    types:
      - completed

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Deploy to Koyeb
        run: koyeb service redeploy 02f95183-5174-44af-b687-4cf9d14e4f1f
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}